name: amar_diet
description: Apon Susthota (আপন সুস্থতা) — Bangladeshi diabetic meal recommendation app
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.5.6
  provider: ^6.1.2
  intl: ^0.20.2
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  fl_chart: ^1.2.0
  animated_notch_bottom_bar: 1.0.4
  video_player: ^2.9.1
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  pdf: ^3.13.0
  permission_handler: ^11.3.1
  printing: ^5.13.4
  bangla_pdf: ^1.0.6
  flutter_local_notifications: 18.0.1
  syncfusion_flutter_charts: ^28.1.33
  timezone: ^0.9.4
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/logo.png
    - assets/data/bd_geo.json
    - assets/splash/1.png
    - assets/splash/2.png
    - assets/splash/3.png
    - assets/vids/main.mp4
  fonts:
    - family: NotoSansBengali
      fonts:
        - asset: assets/fonts/NotoSansBengali-Regular.ttf
        - asset: assets/fonts/NotoSansBengali-Bold.ttf
          weight: 700