-- ============================================================
-- 21_profile_photos.sql
-- Profile photo upload support.
--   * Adds `avatar_url` (nullable text) to public.user_profiles so the
--     profile screen can render the photo directly from the row.
--   * Adds `photo_upload_count` (default 0) to public.user_profiles
--     so the client can enforce "max 2 uploads per user" without
--     having to count rows separately.
--   * Creates a private Storage bucket `profile` (idempotent) with
--     per-user RLS so each user can only write/read their own photo.
--
-- Run AFTER 01_schema.sql. Safe to re-run.
-- ============================================================

-- 1. Columns on the profile row --------------------------------------------
alter table public.user_profiles
  add column if not exists avatar_url text,
  add column if not exists photo_upload_count int not null default 0;

-- 2. RLS is already enabled on user_profiles (see 01_schema.sql) and the
--    existing "Users manage their own profile" policy lets each user
--    update their own row, which is all we need for avatar_url /
--    photo_upload_count to be writable from the Flutter client.

-- 3. Private Storage bucket `profile` -------------------------------------
--    Private means the file URL is only readable with a signed URL
--    generated by the authenticated owner.
insert into storage.buckets (id, name, public)
values ('profile', 'profile', false)
on conflict (id) do update set public = excluded.public;

-- 4. Storage RLS policies --------------------------------------------------
--    The user can upload (insert) only inside their own folder
--    `<auth.uid()>/...`. We require the first path segment of the
--    object name to equal the authenticated user's id.

drop policy if exists "Users upload their own profile photo"
  on storage.objects;
create policy "Users upload their own profile photo"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'profile'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users update their own profile photo"
  on storage.objects;
create policy "Users update their own profile photo"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'profile'
    and (storage.foldername(name))[1] = auth.uid()::text
  )
  with check (
    bucket_id = 'profile'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users read their own profile photo"
  on storage.objects;
create policy "Users read their own profile photo"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'profile'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users delete their own profile photo"
  on storage.objects;
create policy "Users delete their own profile photo"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'profile'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- 5. Server-side RPC: increment the photo_upload_count atomically and
--    refuse if the user has already uploaded 2 photos. The client also
--    gates on this count, but doing it server-side stops a tampered
--    client from sneaking in a 3rd upload.
create or replace function public.bump_photo_upload_count()
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count int;
begin
  update public.user_profiles
     set photo_upload_count = photo_upload_count + 1,
         updated_at = now()
   where user_id = auth.uid()
   returning photo_upload_count into v_count;

  if v_count is null then
    raise exception 'Profile row not found for current user.';
  end if;

  if v_count > 2 then
    -- Roll back the increment so the limit is enforced.
    update public.user_profiles
       set photo_upload_count = photo_upload_count - 1
     where user_id = auth.uid();
    raise exception 'Profile photo upload limit reached (max 2).'
      using errcode = 'P0001';
  end if;

  return v_count;
end;
$$;

revoke all on function public.bump_photo_upload_count() from public;
grant execute on function public.bump_photo_upload_count() to authenticated;
