// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5gVDdZpa8UqMe99DzgisXqLWACGS2e6Q',
    appId: '1:721436407997:web:b18b463e08c3d3c643dfd4',
    messagingSenderId: '721436407997',
    projectId: 'apon-susthota',
    authDomain: 'apon-susthota.firebaseapp.com',
    storageBucket: 'apon-susthota.firebasestorage.app',
    measurementId: 'G-FLZBGTXET6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-eGSpMFkDRxYXcn_nW2sbI-rjaRd4QGY',
    appId: '1:721436407997:android:002b36b90da4ea6043dfd4',
    messagingSenderId: '721436407997',
    projectId: 'apon-susthota',
    storageBucket: 'apon-susthota.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG7mIBLpf8a3BkrKV3fzwDoC6ruOe3_s8',
    appId: '1:721436407997:ios:33361e9f9c2ae66043dfd4',
    messagingSenderId: '721436407997',
    projectId: 'apon-susthota',
    storageBucket: 'apon-susthota.firebasestorage.app',
    iosBundleId: 'com.example.diabeticsmeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG7mIBLpf8a3BkrKV3fzwDoC6ruOe3_s8',
    appId: '1:721436407997:ios:33361e9f9c2ae66043dfd4',
    messagingSenderId: '721436407997',
    projectId: 'apon-susthota',
    storageBucket: 'apon-susthota.firebasestorage.app',
    iosBundleId: 'com.example.diabeticsmeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5gVDdZpa8UqMe99DzgisXqLWACGS2e6Q',
    appId: '1:721436407997:web:95d48c4a7f38914743dfd4',
    messagingSenderId: '721436407997',
    projectId: 'apon-susthota',
    authDomain: 'apon-susthota.firebaseapp.com',
    storageBucket: 'apon-susthota.firebasestorage.app',
    measurementId: 'G-0X6ZSL5XNG',
  );
}
